version: '3.9'

services:
  app:
    build:
      context: .
    container_name: application
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    container_name: food_service_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_server
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
  celery:
    build:
      context: .
    container_name: celery_worker
    command: celery -A food_delivery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - app
      - redis
      - rabbitmq
    env_file:
      - .env

volumes:
  postgres_data: